"""unique active booking per slot

Revision ID: 2ead4d9ddf22
Revises: 790bcaefe358
Create Date: 2026-09-26 16:44:03.840195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ead4d9ddf22'
down_revision: Union[str, None] = '790bcaefe358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_bookings_active_slot', 'bookings', ['user_id', 'centre_id', 'test_id', 'appointment_at'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'CONFIRMED')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_bookings_active_slot', table_name='bookings', postgresql_where=sa.text("status IN ('PENDING', 'CONFIRMED')"))
    # ### end Alembic commands ###
