"""add retry fields to webhook events

Revision ID: 821144ee17aa
Revises: efcb310d4d2e
Create Date: 2026-09-28 00:14:04.479666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821144ee17aa'
down_revision: Union[str, None] = 'efcb310d4d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('webhook_events', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('webhook_events', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('webhook_events', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_webhook_events_unprocessed', 'webhook_events', ['next_retry_at'], unique=False, postgresql_where=sa.text('processed_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_events_unprocessed', table_name='webhook_events', postgresql_where=sa.text('processed_at IS NULL'))
    op.drop_column('webhook_events', 'next_retry_at')
    op.drop_column('webhook_events', 'last_error')
    op.drop_column('webhook_events', 'attempts')
    op.drop_column('webhook_events', 'status')
    # ### end Alembic commands ###
