"""add payment idempotency key and webhook result

Revision ID: efcb310d4d2e
Revises: 2ead4d9ddf22
Create Date: 2026-09-26 16:47:49.941903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efcb310d4d2e'
down_revision: Union[str, None] = '2ead4d9ddf22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.create_unique_constraint('payments_idempotency_key_key', 'payments', ['idempotency_key'])
    op.add_column('webhook_events', sa.Column('result', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_events', 'result')
    op.drop_constraint('payments_idempotency_key_key', 'payments', type_='unique')
    op.drop_column('payments', 'idempotency_key')
    # ### end Alembic commands ###
